### ISSUE TITLE
ValueError: type of None unknown: <class 'NoneType'>. Should be one of a python, numpy, pytorch or tensorflow object.

### ISSUE THREAD

**Issue by lxystaruni** [VICO-UoE/CIN-SSL#1]
Excuse me, I encountered an issue while running your code. Can you help me? Besides, the requirements.txt is empty. Could you please update it?
<img width="842" alt="image" src="https://github.com/VICO-UoE/CIN-SSL/assets/126388216/32693ec9-1990-44f6-9ad9-436224c5ba29">

**Comment by goelarushi** [comment]
Did you try to create the environment following https://github.com/VICO-UoE/CIN-SSL?tab=readme-ov-file#environment-installation
Looks like environment issues. I will try to reproduce the error on my side though. Let me know if it works after installing the same env requirements.

**Comment by lxystaruni** [comment]
Thanks for your reply. I basically created the environment following https://github.com/VICO-UoE/CIN-SSL?tab=readme-ov-file#environment-installation, but I replaced spacy 3.4.1 with spacy 3.7.2 because spacy 3.4.1 had a problem: "TypeError: issubclass() arg 1 must be a class". When I used spacy 3.7.2, the problem was solved. I will continue to check my environment.
